# Generated by Django 3.2.4 on 2022-01-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dno', models.BigAutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('eno', models.BigAutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=40)),
                ('design', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('dno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreignapp.dept')),
            ],
        ),
    ]
