# Generated by Django 3.2.4 on 2022-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreignapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
