# Generated by Django 3.2.4 on 2022-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heriapp.person')),
                ('course', models.CharField(max_length=30)),
                ('fee', models.IntegerField()),
                ('mock', models.IntegerField()),
            ],
            bases=('heriapp.person',),
        ),
        migrations.CreateModel(
            name='techinal',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='heriapp.person')),
                ('design', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
            bases=('heriapp.person',),
        ),
    ]
