# Generated by Django 3.2.4 on 2022-01-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singleapp', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='singleapp.address')),
                ('accno', models.BigIntegerField()),
                ('accname', models.CharField(max_length=50)),
                ('db', models.BigIntegerField()),
                ('edate', models.CharField(max_length=10)),
                ('cvv', models.IntegerField()),
            ],
            bases=('singleapp.address',),
        ),
    ]
