# Generated by Django 3.2.4 on 2022-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publish', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('dop', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('website', models.URLField()),
            ],
        ),
    ]
