# Generated by Django 3.2.4 on 2022-01-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('sphone', models.BigIntegerField()),
                ('scourse', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('tid', models.BigAutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=50)),
                ('temail', models.EmailField(max_length=254)),
                ('tphone', models.BigIntegerField()),
                ('tsubject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('trainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='multiapp.trainer')),
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multiapp.student')),
                ('insti', models.CharField(max_length=30)),
                ('batchcode', models.CharField(max_length=20)),
                ('attendance', models.IntegerField()),
                ('batch', models.TimeField()),
            ],
            bases=('multiapp.student', 'multiapp.trainer'),
        ),
    ]
